/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author asepwahyudi
 */
public class JFrameDosen extends javax.swing.JFrame {
    public DefaultTableModel model;  
    private String idProdi = "";

    /**
     * Creates new form JFrameDosen
     */
    public JFrameDosen() {
        initComponents();
        HeaderTable();
    }
    
    public void HeaderTable()
    {
       //memberi penamaan pada kolom Jtabel
        model=new DefaultTableModel();
        jTableProdi.setModel(model);
        model.addColumn("Kode Prodi");
        model.addColumn("Nama Prodi");
        model.addColumn("Ketua Prodi");
        model.addColumn("Sekjur");
        model.addColumn("Date Modify");
        model.addColumn("Date Create"); 
        AturKolom();
        datatotabel();
    }
    
    public void AturKolom()
    {
        TableColumn kolom;
        jTableProdi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        kolom = jTableProdi.getColumnModel().getColumn(0); 
        kolom.setPreferredWidth(100); 
        kolom = jTableProdi.getColumnModel().getColumn(1); 
        kolom.setPreferredWidth(200);
        kolom = jTableProdi.getColumnModel().getColumn(2); 
        kolom.setPreferredWidth(200);
        kolom = jTableProdi.getColumnModel().getColumn(3); 
        kolom.setPreferredWidth(200);
        kolom = jTableProdi.getColumnModel().getColumn(4); 
        kolom.setPreferredWidth(150);
        kolom = jTableProdi.getColumnModel().getColumn(5); 
        kolom.setPreferredWidth(150);
    }
    
     public void datatotabel()
    {
        //menghapus isi table tblGaji
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
        try{
            //membuat statemen pemanggilan data pada table jtbluser dari database
              Statement stat=(Statement)KoneksiDB.Getkoneksi().createStatement();
              
              String sql="select *from tProdi";
              ResultSet rs=stat.executeQuery(sql);
               //penelusuran baris pada tabel tuser dari database
             while (rs.next())
             {
                 Object[] fieldx=new Object[6];
                 fieldx[0]=rs.getString("kd_prodi");
                 fieldx[1]=rs.getString("nama_prodi");         
                 fieldx[2]=rs.getString("ketua_prodi");
                 fieldx[3]=rs.getString("sekjur");
                 fieldx[4]=rs.getString("datecreate");
                 fieldx[5]=rs.getString("datemodify");
                 
                 model.addRow(fieldx);
              }             
        }//akhir try
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage() );   
        }
    }
     
    private void clearFields() {
        txt_kdprodi.setText("");
        txt_nama.setText("");
        txt_ketua.setText("");
        txt_sekjur.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdi = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_ketua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_sekjur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_kdprodi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdi);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel1.setText("Form Prodi");

        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namaKeyPressed(evt);
            }
        });

        txt_ketua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ketuaKeyPressed(evt);
            }
        });

        jLabel2.setText("Nama Prodi");

        jLabel3.setText("Ketua Prodi");

        jLabel4.setText("Sekjur");

        txt_sekjur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sekjurActionPerformed(evt);
            }
        });

        jLabel5.setText("Kode Prodi");

        txt_kdprodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kdprodiActionPerformed(evt);
            }
        });
        txt_kdprodi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_kdprodiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama)
                            .addComponent(txt_ketua)
                            .addComponent(txt_sekjur, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txt_kdprodi)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_simpan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_keluar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_kdprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ketua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sekjur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus)
                    .addComponent(btn_keluar))
                .addGap(72, 72, 72))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String kdProdi = txt_kdprodi.getText();
        String namaProdi = txt_nama.getText();
        String ketuaProdi = txt_ketua.getText();
        String sekjur = txt_sekjur.getText();

        if (namaProdi.isEmpty() || ketuaProdi.isEmpty() || sekjur.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String query;
        boolean isInsert = idProdi.isEmpty(); 

        if (isInsert) {
            query = "INSERT INTO tProdi (kd_prodi, nama_prodi, ketua_prodi, sekjur, datecreate, datemodify) VALUES (?, ?, ?, ?, NOW(), NOW())";
        } else {
            query = "UPDATE tProdi SET nama_prodi = ?, ketua_prodi = ?, sekjur = ?, datemodify = NOW() WHERE kd_prodi = ?";
        }

        try (Connection conn = KoneksiDB.Getkoneksi();
             PreparedStatement pstmt = conn.prepareStatement(query)) {

            if (isInsert) {
                pstmt.setString(1, kdProdi);
                pstmt.setString(2, namaProdi);
                pstmt.setString(3, ketuaProdi);
                pstmt.setString(4, sekjur);
            } else {
                pstmt.setString(1, namaProdi);
                pstmt.setString(2, ketuaProdi);
                pstmt.setString(3, sekjur);
                pstmt.setString(4, idProdi);
            }

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, isInsert ? "Data berhasil disimpan!" : "Data berhasil diperbarui!");

            idProdi = ""; 
            datatotabel();
            clearFields();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
            { // begin 
                txt_ketua .requestFocus();   //panggil komponen yang akan di tuju 
            }  //end if

    }//GEN-LAST:event_txt_namaKeyPressed

    private void txt_ketuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ketuaKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
            { // begin 
                txt_sekjur .requestFocus();   //panggil komponen yang akan di tuju 
            }  //end if
    }//GEN-LAST:event_txt_ketuaKeyPressed

    private void jTableProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdiMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTableProdi.getSelectedRow();
        if (selectedRow != -1) {
            idProdi = jTableProdi.getValueAt(selectedRow, 0).toString(); 

            txt_kdprodi.setText(jTableProdi.getValueAt(selectedRow, 0).toString());
            txt_nama.setText(jTableProdi.getValueAt(selectedRow, 1).toString());
            txt_ketua.setText(jTableProdi.getValueAt(selectedRow, 2).toString());
            txt_sekjur.setText(jTableProdi.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_jTableProdiMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableProdi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String kodeProdi = jTableProdi.getValueAt(selectedRow, 0).toString();

        if (kodeProdi == null || kodeProdi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode Prodi tidak valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String query = "DELETE FROM tProdi WHERE kd_prodi = ?";

            try (Connection conn = KoneksiDB.Getkoneksi();
                 PreparedStatement pstmt = conn.prepareStatement(query)) {

                pstmt.setString(1, kodeProdi);
                int affectedRows = pstmt.executeUpdate();

                if (affectedRows > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    datatotabel();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau gagal dihapus.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_sekjurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sekjurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sekjurActionPerformed

    private void txt_kdprodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kdprodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kdprodiActionPerformed

    private void txt_kdprodiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kdprodiKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
            { // begin 
                txt_nama .requestFocus();   //panggil komponen yang akan di tuju 
            }  //end if
    }//GEN-LAST:event_txt_kdprodiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdi;
    private javax.swing.JTextField txt_kdprodi;
    private javax.swing.JTextField txt_ketua;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_sekjur;
    // End of variables declaration//GEN-END:variables
}
