/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;
import java.awt.event.KeyEvent;
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.Statement;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author asepwahyudi
 */
public class JFrameDosen extends javax.swing.JFrame {
    public DefaultTableModel model;  
    String kd_dosen = "";

    /**
     * Creates new form JFrameDosen
     */
    public JFrameDosen() {
        initComponents();
        HeaderTable();
    }
    
    public void HeaderTable()
    {
       //memberi penamaan pada kolom Jtabel
        model=new DefaultTableModel();
        jTableDosen.setModel(model);
        model.addColumn("Kode Dosen");
        model.addColumn("Nama Dosen");
        model.addColumn("Alamat");
        model.addColumn("Date Modify");
        model.addColumn("Date Create"); 
        AturKolom();
        datatotabel();
    }
    
    public void AturKolom()
    {
        TableColumn kolom;
        jTableDosen.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        kolom = jTableDosen.getColumnModel().getColumn(0); 
        kolom.setPreferredWidth(100); 
        kolom = jTableDosen.getColumnModel().getColumn(1); 
        kolom.setPreferredWidth(200);
        kolom = jTableDosen.getColumnModel().getColumn(2); 
        kolom.setPreferredWidth(250);
        kolom = jTableDosen.getColumnModel().getColumn(3); 
        kolom.setPreferredWidth(150);
        kolom = jTableDosen.getColumnModel().getColumn(4); 
        kolom.setPreferredWidth(150);
    }
    
     public void datatotabel()
    {
        //menghapus isi table tblGaji
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
        try{
            //membuat statemen pemanggilan data pada table jtbluser dari database
              Statement stat=(Statement)KoneksiDB.Getkoneksi().createStatement();
              
              String sql="select *from tDosen";
              ResultSet rs=stat.executeQuery(sql);
               //penelusuran baris pada tabel tuser dari database
             while (rs.next())
             {
                 Object[] fieldx=new Object[5];
                 fieldx[0]=rs.getString("kd_dosen");
                 fieldx[1]=rs.getString("nama_dosen");         
                 fieldx[2]=rs.getString("alamat");
                 fieldx[3]=rs.getString("datecreate");
                 fieldx[4]=rs.getString("datemodify");
                 
                 model.addRow(fieldx);
              }             
        }//akhir try
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage() );   
        }
    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDosen = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDosen);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel1.setText("Form dosen");

        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namaKeyPressed(evt);
            }
        });

        txt_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_alamatKeyPressed(evt);
            }
        });

        jLabel2.setText("Nama Dosen");

        jLabel3.setText("Alamat Dosen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_keluar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus)
                    .addComponent(btn_keluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (!txt_nama.getText().isEmpty() || txt_alamat.getText().isEmpty()) 	
        {
                Statement StrU=(Statement)KoneksiDB.Getkoneksi().createStatement();  
                Statement StrI=(Statement)KoneksiDB.Getkoneksi().createStatement();  
                Statement Str=(Statement)KoneksiDB.Getkoneksi().createStatement();  
            if(!kd_dosen.equals("")) {
                                 //jika data sudah ada
                StrU.executeUpdate("update trole set datemodify='"+CreateDate+"',nama_dosen='"+ txt_nama.getText() +"' where kd_dosen='"+ kd_dosen +"'" ); 
                JOptionPane.showMessageDialog(null, "Data Sudah  Ubah","Update",JOptionPane.INFORMATION_MESSAGE);
                jTextField_Role.requestFocus();
                HeaderTable();
                rool_id="";
                jTextField_Role.setText("");
                jTextField_Role.requestFocus();

            } else {
                
            }
        }else{
            //isi dengan CRUD Insert data dan update data
            JOptionPane.showMessageDialog(null,"Role Name Belum Di Isi"); 
           txt_nama.requestFocus(); 
        }

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
            { // begin 
                txt_alamat .requestFocus();   //panggil komponen yang akan di tuju 
            }  //end if

    }//GEN-LAST:event_txt_namaKeyPressed

    private void txt_alamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alamatKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
            { // begin 
                txt_alamat .requestFocus();   //panggil komponen yang akan di tuju 
            }  //end if
    }//GEN-LAST:event_txt_alamatKeyPressed

    private void jTableDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDosenMouseClicked
        // TODO add your handling code here:
        txt_nama.setText(model.getValueAt(jTableDosen.getSelectedRow(),1)+"");
        txt_alamat.setText(model.getValueAt(jTableDosen.getSelectedRow(),2)+"");

        kd_dosen=(model.getValueAt(jTableDosen.getSelectedRow(),0)+"");
    }//GEN-LAST:event_jTableDosenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDosen;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
